name: Python_Django application

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Django
          pip install Django-filter
          pip install Django-auditlog
          pip install selenium
          python -m venv venv
          source venv/bin/activate

      # Install necessary packages for headless browser support
      - name: Install required packages for headless browser
        run: sudo apt-get install -y xvfb

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Django
          pip install Django-filter
          pip install Django-auditlog
          pip install selenium
          python -m venv venv
          source venv/bin/activate

      # Install necessary packages for headless browser support
      - name: Install required packages for headless browser
        run: sudo apt-get install -y xvfb

      - name: Test
        run: |
          # Start Xvfb
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x16 &

          # Run the test script
          python test.py
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'appswiam'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_b5d8c4c9b240465bb4e4d43344e93847 }}
          package: .
