name: Python_Django application

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Django
          pip install Django-filter
          pip install Django-auditlog
          pip install selenium
          python -m venv venv
          source venv/bin/activate

      # Install necessary packages for headless browser support
      - name: Install required packages for headless browser
        run: sudo apt-get install -y xvfb

      - name: Test
        run: |
          # Start Xvfb
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x16 &

          # Run the test script
          python test.py
