name: Python_Django application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - name: Clean up previous environment
        run: |
           rm -rf venv
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Django
          pip install Django-filter
          pip install Django-auditlog
          pip install selenium
          python -m venv venv 
          source venv/bin/activate 
         
      - name: Test 
        run: |
          python test.py
   
